# Generated by Django 4.1.1 on 2022-09-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="isactive",
            field=models.BooleanField(default=True),
        ),
    ]
